name: Python application

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Setup pipenv
      run: |
        python -m pip install --upgrade pip
        pip install --user pipenv
    - name: Install dependencies
      run: pipenv install --dev
    - name: Lint
      run: pipenv run flake8 --exit-zero
    - name: Test
      run: pipenv run pytest
