name: Python application

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        gdal: ['true', '']
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        cache: pipenv
        python-version: "3.9"
    - name: Setup pipenv
      run: |
        python -m pip install --upgrade pip
        pip install --user pipenv
    - name: Install GDAL
      uses: lyricwulf/abc@v1
      with:
        macos: gdal
        linux: libgdal30
    - name: Install dependencies
      run: pipenv install --dev
    - name: Install GDAL Python wrapper
      if: matrix.gdal
      run: pipenv install gdal==3.4.1   # Python lib versions MUST be the same as the corresponding system lib versions
    - name: Lint
      run: pipenv run flake8 --exit-zero
    - name: Test
      run: pipenv run pytest
