name: Test

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          cache: poetry
          python-version: "3.9"
      - name: Install dependencies
        run: poetry install
# TODO run tests
