name: Build

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: "3.10"
      - name: Install dependencies
        run: poetry install
      - name: Test
        run: poetry run pytest
  black:
    name: "Black"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: "3.10"
      - name: Install dependencies
        run: poetry install
      - name: Black
        run: poetry run black src/
  mypy:
    name: "MyPy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: "3.10"
      - name: Install dependencies
        run: poetry install
      - name: MyPy
        run: poetry run mypy
